#!/bin/bash

# Use image label to cleanup possible orphaned images.
oImgs=$(buildah images | grep -F '<none>' | awk '{print $3}')
for img in $oImgs ; do
    if buildah inspect $img | grep -q '"AUTOMATION_CONTAINER_IMAGE": "sso"'; then
        buildah rmi --force $img
    fi
done

if [ "$1" == "purge" ]; then
    if podman volume ls | awk '{print $2}' | grep -q ^sso$; then
        printf "\n* Clean up sso volume...\n"
        podman volume rm -f sso
        podman volume rm -f sso-db
    fi
fi

# Force debconf cleanup.
echo PURGE | debconf-communicate automation-interface-sso-container

exit 0
